name: Broken Clock Brewing Cooperative
favicon: null
layout_spectrum: 0.73713
typography_spectrum: 0.49876
title: Broken Clock Brewing
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#5f5f5f'
    - '#cfcfcf'
    - '#9f9f9f'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
