name: Broken Clock Brewing Cooperative
favicon: null
layout_spectrum: 1
typography_spectrum: 0.43733
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#5f5f5f'
    - '#cfcfcf'
    - '#9f9f9f'
  brandStrength: 0.5
  lightness: 0.10052659502252936
  saturation: 0.03776922123506665
  rhythmicContrast: 0.11707724421285093
purpose: []
